### ISSUE TITLE
add error return values to interactions to consensus module

### ISSUE THREAD

**Issue by jeffrey990219** [rgreen312/OwlPlace#31]

**Comment by gvacaliuc** [comment]
In order to differentiate between different types of errors, there are methods in the apiserver that should return error values.   Specifically, `GetLastUserModification`.  

I'll add more to this later...

**Comment by gvacaliuc** [comment]
#39 helps a bit with this, but we still can't distinguish between error types.  I'm going to restructure some of the interactions with the consensus module and will fix this issue.
