### ISSUE TITLE
Is there any way we can make the docker compile faster?

### ISSUE THREAD

**Issue by southpawac** [rgreen312/OwlPlace#44]
This would make it easier to debug

**Comment by gvacaliuc** [comment]
Yes, we can do a few things to speed up image build time.

Our (non-go) dependencies don't change, meaning the build container won't change.  We can pull the `go build` step out and add a Make directive to run `go build` in the build container and cache build outputs on disk.  e.g. something like this `docker run -v /tmp/owlplace-cache:/path/to/go/cache/` --workdir /app owlplace-build go build`.

Additionally, everytime we run `docker build...` we also package up the lean deployment image, which installs some apk packages everytime.  We don't need to do any of that to just verify compilation.
